### ISSUE TITLE
Plugin Not Working.

### ISSUE THREAD

**Issue by NamVr** [R-J/AddWPInfo#1]
When I enable the plugin it says - Add WordPress Info plugin requires: tagging.
And I also added 3-4 tage in tagging group in the discussions. Please help me figure out my mistake.

**Comment by R-J** [comment]
The time it has been created "Tagging" has been an extra plugin, now it is a core feature. The line in the PluginInfo which requires that plugin should be deleted. But that plugin has been for very specific needs. You would have to customize it numerous ways to make it working for you.

I doubt that it would be working without problems with the new Keystone theme.

**Comment by NamVr** [comment]
I did what you told.
1. I went to my ftp server, and then edited the class.addwpinfo.plugin.php
2. I made this line as a comment - like this "//'RequiredPlugins' => array('Tagging' => '1.6.2'),"
3. Then I cleared my Addon Cache and then reloaded the website.

Everything was fine and thanks for your quick support.. **BUT** When i went to -
https://forum.example.com/dashboard/settings/plugins and enable the plugin **Add Wordpress Info**
It says Plugin enabled. When i clicked the settings icon- ERROR MESSAGE - **View not found.**

Please help and thanks for your help

**Comment by R-J** [comment]
Sorry I haven't seen this. Is this still an open question? If yes, make sure that you have spelled the plugins folder correctly. This is the line of code where the view is fetched:
` $Sender->Render('settings', '', 'plugins/AddWPInfo');`
Here you can see the spelling that the plugins folder **needs** to have. Upper/lower case matters.

**Comment by NamVr** [comment]
Oh! I will try. Thanks!
